# Generated by Django 5.1.5 on 2025-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(default='Qwen/Qwen2.5-0.5B-Instruct', max_length=100),
        ),
    ]
